version: '3.7'

services:
  fe2_kartengenerierung:
    image: odin568/fe2_kartengenerierung:latest
    container_name: fe2_kartengenerierung
    ports:
      - "8080:8080"
    restart: always
    # Define external mapping to access maps from other processes
#    volumes:
#      - /tmp/maps:/maps
    healthcheck:
      test: curl --insecure --fail http://localhost:8080/actuator/health || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    environment:
      - GCP_CACHING_ENABLED=true
      # required
      - GCP_MAPS_APIKEY=123456
      # optional
      - GCP_MAPS_SIGNINGKEY=123456
      # optional
      - GCP_DIRECTIONS_APIKEY=123465
      # optional
      - GCP_DIRECTIONS_ORIGIN_LAT=49.123
      - GCP_DIRECTIONS_ORIGIN_LNG=10.123
      # required
      - OUTPUT_FOLDER=/maps
      # required
      - OUTPUT_FORMAT=png32
      # optional
      - WK_TOKEN=123456
      # optional
      - WK_CUSTOMICONS=1=https://bit.ly/Hydrant16O.png;2=https://bit.ly/Hydrant16U.png;3=https://bit.ly/Hydrant16W.png
