version: '3'
services:
  fe2_kartengenerierung:
    image: odin568/fe2_kartengenerierung:latest
    container_name: fe2_kartengenerierung
    restart: always
    ports:
      - 8080:8080
    network_mode: host
    environment:
      gcp.maps.apiKey: 123456
      gcp.maps.signingKey: 123456
      gcp.directions.apiKey: 123465
      gcp.directions.origin.lat: 49.123
      gcp.directions.origin.lng: 10.123
      output.folder: /maps
      output.format: png32
      wk.token: 123456
      wk.customIcons: 1=https://bit.ly/Hydrant16O.png;2=https://bit.ly/Hydrant16U.png;3=https://bit.ly/Hydrant16W.png
    volumes:
      - /tmp/maps:/maps
    healthcheck:
      test: "curl --fail --silent http://localhost:8080/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 2s
      retries: 10