spring:
  main:
    banner-mode: off

management:
  endpoints:
    web:
      cors:
        allowed-headers: '*'
        allowed-origins: '*'
        allowed-methods: '*'
      exposure:
        include:
          - info
          - health
  endpoint:
    health:
      show-details: ALWAYS
  info:
    java:
      enabled: true
  security:
    enabled: false